# Generated by Django 4.2.23 on 2026-01-24 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('investment_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rent_mortgage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('utilities', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('property_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('home_insurance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('car_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('car_insurance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maintenance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('public_transit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('groceries', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dining_out', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('health_insurance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medical_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prescriptions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('clothing', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('personal_care', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('entertainment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subscriptions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit_card_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loan_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('savings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('investments', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('childcare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('education', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gifts_donations', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pet_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('miscellaneous', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Budget Entry',
                'verbose_name_plural': 'Budget Entries',
                'ordering': ['-date'],
            },
        ),
    ]
